name: Run Chaos Experiment
on:
  workflow_dispatch:
defaults:
  run:
    working-directory: /root
jobs:
  Run-Chaos-Experiment:
    runs-on: arc-runner-mo-chaos-driller
    container:
      image: matrixorigin/mo-chaos-driller:latest
      options: --pull always
    steps:
      - name: Run
        run: python main.py